### ISSUE TITLE
`InvalidGasEstimation` error

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/safe-relay-service#67]
This error has been seen when creating an org account (although the creation was successful), and when updating safe version. It's probably not related to a specic transaction, but has to be debugged further.
```
safe_relay_service.relay.services.transaction_service.InvalidGasEstimation: Gas should be at least equal to safe-tx-gas=91064 and base-gas=48516. Current is safe-tx-gas=89950 and base-gas=48516
```

**Comment by JacqueGM** [comment]
related issue - https://github.com/5afe/safe-relay-service/issues/178

**Comment by llunaCreixent** [comment]
This is not observed anymore

**Comment by llunaCreixent** [comment]
@JacqueGM which PR is solving this?

**Comment by llunaCreixent** [comment]
Error not seen anymore
