### ISSUE TITLE
cannot create accounts

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/safe-relay-service#72]
There is a problem with account creation at the moment, where the account are in the account validation step forever. 

An attempt to update the relayer has been made and update the gas for account creation increased, however the issue is still happening

**Comment by llunaCreixent** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/safe-relay-service/72?planning-poker) with Zenhub @JacqueGM

**Comment by llunaCreixent** [comment]
This the loop where it gets stuck: https://github.com/CirclesUBI/circles-core/blob/main/src/utils.js#L965

So more funds need to be located in the accounts in order to finish the deployment of the token

**Comment by JacqueGM** [comment]
Increasing the amout has worked and now accounts can be created again !

**Comment by llunaCreixent** [comment]
However, accounts that have already deployed the Safe contract only, cannot continue the validation

**Comment by llunaCreixent** [comment]
This PR is solving the issue with the accounts that are stuck in the deploy token step.
https://github.com/CirclesUBI/circles-core/pull/162
